behaviors:
  GROUP-BOT:
    trainer_type: poca
    summary_freq: 1
    max_steps: 300000
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 1.0e-6
      beta: 1.0e-3
      epsilon: 0.3
      lambd: 0.9
      num_epoch: 5 
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 50
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  # PARENT-BOT:
  #   trainer_type: poca
  #   summary_freq: 1
  #   hyperparameters:
  #     batch_size: 2
  #     buffer_size: 16
  #     learning_rate: 3.0e-4
  #     beta: 0.7
  #     epsilon: 0.2
  #     lambd: 0.99
  #     num_epoch: 3 
  #     learning_rate_schedule: linear
  #     beta_schedule: constant
  #     epsilon_schedule: linear
  #   network_settings:
  #     normalize: false
  #     hidden_units: 32
  #     num_layers: 20
  #   self_play:
  #     save_steps: 50000
  #     team_change: 200000
  #     swap_steps: 2000
  #     window: 10
  #     play_against_latest_model_ratio: 0.5
  #     initial_elo: 1200.0

  # HEX:
  #   trainer_type: poca
  #   summary_freq: 1
  #   hyperparameters:
  #     batch_size: 2
  #     buffer_size: 16
  #     learning_rate: 3.0e-4
  #     beta: 0.7
  #     epsilon: 0.2
  #     lambd: 0.99
  #     num_epoch: 3
  #     learning_rate_schedule: linear
  #     beta_schedule: constant
  #     epsilon_schedule: linear
  #   network_settings:
  #     normalize: false
  #     hidden_units: 32
  #     num_layers: 20
  #   self_play:
  #     save_steps: 50000
  #     team_change: 200000
  #     swap_steps: 2000
  #     window: 10
  #     play_against_latest_model_ratio: 0.5
  #     initial_elo: 1200.0

  # CELESTIAL:
  #   trainer_type: poca
  #   summary_freq: 1
  #   hyperparameters:
  #     batch_size: 2
  #     buffer_size: 16
  #     learning_rate: 3.0e-4
  #     beta: 0.7
  #     epsilon: 0.2
  #     lambd: 0.99
  #     num_epoch: 3
  #     learning_rate_schedule: linear
  #     beta_schedule: constant
  #     epsilon_schedule: linear
  #   network_settings:
  #     normalize: false
  #     hidden_units: 32
  #     num_layers: 20
  #   self_play:
  #     save_steps: 50000
  #     team_change: 200000
  #     swap_steps: 2000
  #     window: 10
  #     play_against_latest_model_ratio: 0.5
  #     initial_elo: 1200.0

  # SHIP:
  #   trainer_type: poca
  #   summary_freq: 1
  #   hyperparameters:
  #     batch_size: 2
  #     buffer_size: 16
  #     learning_rate: 3.0e-4
  #     beta: 0.7
  #     epsilon: 0.2
  #     lambd: 0.99
  #     num_epoch: 3
  #     learning_rate_schedule: linear
  #     beta_schedule: constant
  #     epsilon_schedule: linear
  #   network_settings:
  #     normalize: false
  #     hidden_units: 32
  #     num_layers: 20
  #   self_play:
  #     save_steps: 50000
  #     team_change: 200000
  #     swap_steps: 2000
  #     window: 10
  #     play_against_latest_model_ratio: 0.5
  #     initial_elo: 1200.0